# color
grn="\e[92m"
# ASCII
echo -e "$grn   .AMMMMMMMMMMA. "
echo "        .AV. :::.:.:.::MA. "
echo "       A  :..        : .:`A "
echo "      A ..              . `A. "
echo "    A  :.    :::::::::  : :`A "
echo "    M  .    :::.:.:.:::  . .M "
echo "    M  :   ::.:.....::.:   .M "
echo "    V : :.::.:........:.:  :V "
echo "   A  A:    ..:...:...:.   A A "
echo "  .V  MA:.....:M.::.::. .:AM.M "
echo " A'  .VMMMMMMMMM:.:AMMMMMMMV: A "
echo ":M .  .`VMMMMMMV.:A `VMMMMV .:M: "
echo " V.:.  ..`VMMMV.:AM..`VMV' .: V "
echo "  V.  .:. .....:AMMA. . .:. .V "
echo "    VMM...: ...:.MMMM.: .: MMV "
echo "      `VM: . ..M.:M..:::M "
echo "       `M::. .:.... .::M "
echo "         M:.  :. .... ..M "
echo "        V:  M:. M. :M .V "
echo "        `V.:M.. M. :M.V "
