
# color
grn="\e[92m"
rset="\e[0m"
# ASCII
echo -e "$grn                      :::!~!!!!!:.$rset"
echo -e "$grn                  .xUHWH!! !!?M88WHX:.$rset"  
echo -e "$grn                .X*#M@$!!  !X!M|||||||WWx:.$rset" 
echo -e "$grn               :!!!!!!?H! :!|!||||||||||||8X:$rset"
echo -e "$grn              !!~  ~:~!! :~!|!||||||||||||||8X:$rset"
echo -e "$grn             :!~::!H!<   ~.U$X!?R||||||||MM!$rset"
echo -e "$grn             ~!~!!!!~~ .:XW|||U!!?|||||||RMM!$rset"
echo -e "$grn               !:~~~ .:!M°T#||||WX??#MRRMMM!$rset"
echo -e "$grn               ~?WuxiW*`   `°#||||8!!!!??!!!$rset"
echo -e "$grm             :X- M||||       `°T#|T~!8$WUXU~$rset"
echo -e "$grn            :%`  ~#|||m:        ~!~ ?|||||$rset"
echo -e "$grn          :!`.-   ~T||||8xx.  .xWW- ~°°##*$rset"
echo -e "$grn .....   -~~:<` !    ~?T#||@@W@*?$$      /`$rset"
echo -e "$grn W$@@M!!! .!~~ !!     .:XUW|W!~ `"~:    :$rset"
echo -e "$grn #°~~`.:x%`!!  !H:   !WM||||Ti.: .!WUn+!`$rset"
echo -e "$grn :::~:!!`:X~ .: ?H.!u "|||B|||!W:U!T$$M~$rset"
echo -e "$grn .~~   :X@!.-~   ?@WTWo(°*|||W$TH|! `$rset"
echo -e "$grn Wi.~!X$?!-~    : ?|||B|Wu(°**$RM!$rset"
echo -e "$grn $R@i.~~ !     :   ~|||||B||en:``$rset"
echo -e "$grn ?MXT@Wx.~    :     ~°##*||||M~°$rset"
